-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 28, 2022 at 08:20 AM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 8.0.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zei`
--

-- --------------------------------------------------------

--
-- Table structure for table `zei`
--

CREATE TABLE `zei` (
  `nume` varchar(20) NOT NULL,
  `porecla` varchar(50) NOT NULL,
  `mitologie` varchar(20) NOT NULL,
  `despre` text NOT NULL,
  `putere` int(10) NOT NULL,
  `viteza` int(10) NOT NULL,
  `inteligenta` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `zei`
--

INSERT INTO `zei` (`nume`, `porecla`, `mitologie`, `despre`, `putere`, `viteza`, `inteligenta`) VALUES
('Afrodita', 'Zeita iubirii', 'greek', 'Simbolurile majore ale Afroditei includ mirtul, trandafirul, porumbelul, vrabia si lebada. Cultul Afroditei provine din religia canaanita antica , dedicat zeitei feniciene Astarte, inrudita cu zeita asiro-babiloniana Ishtar, al carui cult s-a bazat pe cultul sumerian dedicat zeitei Inanna. Principalele centre de cult ale Afroditei erau Cythera, Cipru, Corint si Atena. Festivalul ei principal a fost Afrodisia, care era sarbatorit anual in mijlocul verii. In Laconia, Afrodita a fost venerata ca o zeita razboinica. Ea a fost, de asemenea, zeita protectoare a prostitutiei in Grecia antica, o asociatie care i-a determinat pe eruditii timpurii sa propuna conceptul de „prostitutie sacra” in cultura greco-romana.', 1, 1, 4),
('Anubis', 'Zeul mortii', 'egyptian', 'Anubis (gasit si sub numele de Inpew, Yinepu sau Anpu) este numele zeului ce ghida spiritele mortilor in lumea de dincolo. Acesta este supranumit „Zeul Tinutului Sfant” si al lui Khentamentiu (un zeu precedent lui Anubis). Deoarece egiptenii credeau ca Valea mortilor se afla spre vest, acestia il denumeau si „Regele Vestului”. Venerarea lui Anubis pare a exista din cele mai vechi timpuri ale Egiptului Antic, fiind posibil chiar mai veche decat cea a lui Osiris - acest fapt fiind confirmat de asocierea sa cu Ochiul lui Horus si de catre textele inscriptionate in mormantul faraonului Unas. In textele mormantului lui Unas se precizeaza urmatoarele: „Unas alaturandu-se spiritelor, acestea trei fiind Anubis, apoi Amenti si apoi Osiris”. ', 3, 4, 4),
('Apollo', 'Zeul soarelui', 'greek', 'Apollo (Greaca din Attica, Ionica si Greaca homerica: Ἀπόλλων, Apollon (GEN Ἀπόλλωνος); Dorica: Ἀπέλλων, Apellon; Greaca din Ahaia: Ἀπείλων, Apeilon; Eolica: Ἄπλουν, Aploun; Latina: Apollo)\r\nEtimologia numelui zeului este incerta. Conform unor specialisti, luna Apellaios (Ἀπελλαῖος), ofrandele apellaia (ἀπελλαῖα) si festivalul de initiere al tinerilor, Apellai (ἀπέλλαι), sunt conectate cu termenul doric apella (ἀπέλλα), care insemna „zid”, „gard pentru animale” si mai tarziu „adunare in limitele pietei”. Hesychius din Alexandria leaga numele Apollo de termenul doric ἀπέλλα (apella), care inseamna consiliu, adunare, conferind o latura politica portretului zeului. ', 4, 2, 2),
('Ares', 'Zeul razboiului', 'greek', 'Ares (in greaca veche Ἄρης, insemnand, literalmente, „batalie”) este zeul razboiului in mitologia greaca. El este unul dintre cei doisprezece olimpieni si fiul lui Zeus si Hera. Grecii erau ambivalenti fata de el. El intruchipeaza viteza fizica necesara pentru succesul in razboi, dar poate, de asemenea, sa personifice brutalitatea si pofta de sange, spre deosebire de sora sa Atena, care simbolizeaza strategia militara.\r\nDesi exista multe opere literare despre relatiile sale amoroase si copiii lui, Ares are un rol limitat in mitologia greaca. Cand apare, este adesea umilit. Cand zeul fierar Hefaistos a descoperit ca sotia sa Afrodita avea o aventura cu Ares, i-a prins pe cei doi iubiti intr-o plasa si i-a expus la ridiculizarea de catre ceilalti zei. ', 5, 2, 4),
('Artemis', 'Zeita vanatorii', 'greek', 'Artemis se numara printre cei doisprezece zei olimpieni. A fost una dintre cele mai vechi si venerate zeitati ale Greciei Antice.[2] In perioada clasica a mitologiei elene, Artemis era descrisa ca fiind fiica lui Zeus si a lui Leto, si sora geamana a lui Apollo. Artemis mai era asimilata ca zeita padurilor, nasterii copiilor, virginitatii, fertilitatii, a vanatorii si era reprezentata mereu cu arc si sageti.[3] In perioadele eleniste tarzii, si-a asumat rolul Eileithiei in ajutorul nasterilor. ', 2, 5, 3),
('Atena', 'Zeita strategiei', 'greek', 'Atena Pallas este o zeita din mitologia greaca, asociata cu intelepciunea, artizanatul si razboiul, care a fost ulterior sincretizata cu zeita romana Minerva. Atena a fost considerata patronul si ocrotitoarea diferitelor orase din Grecia, in special orasul Atena, de unde cel mai probabil si-a primit numele. Partenonul de pe Acropola Atenei ii este dedicat. Simbolurile ei majore includ bufnita, maslinul, sarpele si gorgoneionul. In arta, ea este in general reprezentata purtand o casca si tinand o sulita.\r\n\r\nDe la originea ei ca zeitate tutelara, Atena a fost strans asociata cu orasul. Era cunoscuta sub numele de Polias si Poliouchos (ambele derivate din polis, adica „oras-stat”), iar templele ei erau de obicei situate deasupra acropolei fortificate, in partea centrala a orasului. Partenonul de pe Acropola ateniana ii este dedicat, impreuna cu numeroase alte temple si monumente. In calitate de patron al mestesugurilor si tesuturilor, Atena era cunoscuta sub numele de „Ergane”. Era, de asemenea, o zeita razboinica si se credea ca ii conduce pe soldatii in lupta ca Atena Promachos. Principalul ei festival din Atena a fost Panathenaia, care a fost sarbatorit in luna Hekatombaion din mijlocul verii si a fost cel mai important festival din calendarul atenian. ', 4, 2, 5),
('Baldur', 'Zeul luminii', 'norse', 'Baldur (scris si Balder sau Baldr) este in mitologia nordica zeul luminii, al bucuriei, al puritatii, al frumusetii si al inocentei. Iubit atat de zei cat si de oameni, a fost considerat cel mai bun din panteonul germano-scandinav. Cu toate ca avea o putere mica, era inteligent, prietenos si elocvent. Fiu, al lui Odin si al lui Frigg, Baldur a avut-o ca sotie pe Nanna, fiica lui Nep, avand cu ea un fiu: pe Forseti, zeul justitiei.\r\nDatorita maretiei si frumusetii lui, toate fortele naturii au hotarat sa nu il raneasca, in afara de vasc. Diabolicul zeu Loki s-a folosit de aceasta slabiciune. Manipulandu-l pe fratele zeului, Hod, care era orb, el l-a omorat pe Baldur.\r\nilustratie cu zeul Baldur de Jacques Reich\r\nIn mitologia nordica, una din cele mai tragice secvente este moartea lui Baldur, zeul luminii si al puritatii. Sfarsitul fusese anticipat de Frigg, mama sa, zeita cerului, cea care cunoaste destinele tuturor, dar nu are voie sa le dezvaluie nimanui. ', 5, 2, 4),
('Bastet', 'Zeita protectiei', 'egyptian', 'In mitologia egipteana, Bastet a fost zeita lunii si a fecunditatii, ocrotitoarea femeilor gravide, si zeita felinelor, reprezentata fie intr-o forma hieratica, de femeie cu cap de leoaica, fie popular, ca o femeie cu cap de pisica, sau numai ca un cap de pisica (pisica salbatica a fost venerata in Egipt sub dinastia a II-a, in jurul anului 3000 i.Hr.).\r\nBastet a fost sora lui Ra, uneori considerata si fiica acestuia. In unele variante este considerata sora zeitei Isis. Bastet mai era si zeita ocrotitoare a pisicilor. In Valea Regilor s-au gasit mii de mumii de pisici, dar arheologii nu le-au dat importanta. In Egiptul Antic, oricine ucidea o pisica, primea pedeapsa capitala.\r\nBastet era considerata \"Ochiul lui Ra\", deoarece lupta impotriva dusmanilor stapanului sau. ', 2, 2, 4),
('Bragi', 'Zeul poeziei', 'norse', 'În mitologia nordică Bragi este zeul elocvenței și al poeziei și patronul poeților. Tatăl lui este Odin, mama sa Frigg, iar soția sa Idunna.\r\nExistă ipoteze cum că Bragi ar fi fost de fapt un strălucit poet scandinav, care după moarte a fost sanctificat. El i-a spus direct lui Loki că nu era binevenit în Asgard, iar acesta l-a făcut un neștiutor. Nervos, Bragi a amenințat că îi va smulge capul lui Loki pentru a-i opri minciunile sfruntate. Apoi, Loki a fugit din Asgard și a prezis că zeii vor cădea cu toții. Bragi este considerat o adăugare recentă la panteonul germanic datorită multor poeți cele predau discipolilor înțelepciunea sa. Jurăminte importante se făceau deasupra Cupei lui Bragi. ', 1, 1, 5),
('Demeter', 'Zeita agriculturii', 'greek', 'Demetra (greaca: Δημήτηρ) era in mitologia greaca zeita agriculturii, fiind adesea reprezentata cu grane sau o torta, printre altele. Semnificatia numelui acesteia pare sa se traga dintr-un cuvant pentru „mama”, dar orice alta semnificatie este disputata. Se presupune ca aceasta a fost venerata inca din 1200-1400 i.Hr. In alte reprezentari este venerata ca Demetra Thesmosforia „cea care da legi” si in conjunctie cu fiica ei, Persefona, are un rol matern.\r\nDemetra este o zeitate importanta, a avut un cult semnificativ in Grecia antica; efectiv, legendele Demetrei si lacasele sale de cult erau raspandite prin toata civilizatia elenistica (vezi sectiunea Raspandire geografica) evoluand intr-un personaj complex in perceptia elenistica, dupa cum reiese din lista epitetelor asociate acesteia. Totusi, rolul ei in mitologie este secundar. Este fiica lui Cronos si a Rheei; face parte din cea de a doua generatie divina, cea a zeilor olimpieni. Cel mai cunoscut mit al acesteia este rapirea fiicei ei si a lui Zeus, Persefona, de catre Hades, fratele Demetrei, zeul lumii mortilor. Acest mit ofera o explicatie mitologica pentru anotimpuri si sta la baza sarbatorii principale a Demetrei, numita Misterele din Eleusis.', 1, 1, 2),
('Dionysus', 'Zeul vinului', 'greek', 'Dionis (in greaca Διόνυσος Dionysos) era in mitologia greaca zeul vegetatiei, al pomiculturii, al vinului, al extazului si fertilitatii, denumit la romani si Bacchus sau Liber. Era de asemenea poreclit Bromius, Lyaeus (la orfici etc). Dionis era una dintre cele mai importante divinitati cunoscute in antichitate.\r\nDionis era fiul lui Zeus cu muritoarea Semele, fiica regelui teban Cadmos si a Harmoniei. Se numara, deci, din cea de-a doua generatie de zei olimpieni. Semele isi gasi sfarsitul datorita geloasei Hera, care o determinase sa-i ceara lui Zeus sa i se arate in ipostaza sa zeiasca. Zeus i-a aparut intr-adevar, inconjurat de fulgere si tunete, si i-a cauzat astfel moartea. Zeus a reusit totusi sa-si salveze copilul inca nenascut si l-a cusut in propria lui coapsa, de unde il zamisli apoi pe Dionis. Astfel, Dionis este cunoscut drept zeul \"care s-a nascut de doua ori\". Ca sa-si fereasca copilul de Hera, Zeus l-a ascuns in casa regelui Athamas si a sotiei acestuia, Ino. Acolo Dionis a trait imbracat in haine femeiesti pentru a nu fi recunoscut, dar a fost descoperit de Hera si, drept razbunare, mintile lui Ino si lui Athamas au fost luate. Atunci Zeus il incredinteaza pe Dionis prin intermediul lui Hermes nimfelor de la Nisa (vezi si Hyades), mai tarziu lui Silen. ', 1, 1, 3),
('Forseti', 'Zeul justitiei', 'norse', 'Forseti este zeul scandinav al justitiei, al pacii si al adevarului si apartine grupului de zei Aesir. Este fiul zeului Baldur si al zeitei Nanna. Forseti conduce in frumosul palat Glitnir care serveste ca un tribunal de judecata si unde sunt indreptatite disputele. Numele \"Glintir\" inseamna \"luminos\", deoarece palatul avea acoperisurile si tavanele de argint si coloanele de aur, si reflecta atat de bine lumina incat putea fi vazut de departe. Forseti era considerat cel mai intelept si mai chibzuit dintre zeii din Asgard. In opozitie cu Tyr, care avea tendinta sa rezolve pe cale sangeroasa problemele si era stapan al razboiului, Forseti incurajeaza meditatia ca metoda cea mai eficienta de rezolvare a problemelor. Acest zeu nu este mentionat in legenda Ragnarok-ului, ceea ce inseamna ca, in calitate de patron al pacii, a trebuit sa nu ia parte la batalia finala', 5, 2, 1),
('Freya', 'Zeita iubirii', 'norse', 'In mitologia nordica , \'Freyja\' (norvegiana veche: frœyja -Doamna) este o zeita asociata cu dragostea, frumusetea, fertilitatea, sexul, razboiul, aurul si magia. Freyja este proprietarul colierului Brisingamen , se deplaseaza cu un car tras de doua pisici, este insotita de mistretul Hildisvini si poseda o mantie cu pene de soim . Fiind casatorita cu sotul ei Oðr , ea este mama a doua fiice, Hnoss si Gersemi. Impreuna cu fratele ei geaman Freyr, tatal ei Njorðr si mama ei , sora lui Njorðr , este membra a zeilor Vanir . Provenind din vechea norvegiana „Freyja”, formele moderne ale numelui includ „Freya”, „Freyia” si „Freja”.\r\nFreyja stapaneste campul ei ceresc, Folkvangr, unde primeste jumatate din cei care mor in lupta. Cealalta jumatate merge in sala zeului Odin, Valhalla. In Folkvangr se afla sala ei, Sessrumnir. Freyja ajuta alte zeitati permitandu-le sa-si foloseasca mantia cu pene, este invocata in materie de fertilitate si dragoste si este frecvent cautata de puternici jotnar care o doresc sa o ia de sotie. Sotul lui Freyja, zeul Oðr, este frecvent absent. Plange lacrimi de aur rosu pentru el si il cauta sub diferite nume. Freyja are numeroase nume, inclusiv „Gefn”, „Horn”, „Mardoll”, „Syr” si „Vanadis”. ', 2, 2, 4),
('Freyr', 'Zeul fertilitatii', 'norse', 'Fiu al zeului Njord si al zeitei Skadi, frate al zeitei Freya, Freyr este un zeu pasnic, ce apartine mitologiei nordice. El domneste asupra elementelor, a ploii si a soarelui, fiind zeul fecunditatii si a fertilitatii. Detine o nava magica (Skidhbladnir) care are mereu vant bun pentru a transporta marfurile, Freyr fiind si zeul navigatiei. Stapanul elfilor (vezi Elf ), el este cel mai frumos dintre zeii scandinavici.\r\nSe spune ca intr-o zi, Freyr s-a asezat pe tronul lui Odin de unde se vede intreg universul si a zarit-o pe Gerd, o giganta, fiica gigantului Gymir, indragostindu-se de ea, atat de tare incat nu mai putea sa vorbeasca, sa manance si sa doarma. Giganta refuza, la inceput sa devina sotia zeului. In final, Gerd se casatoreste cu Freyr, fiind petita de slujitorul acestuia, Skirnir, care primeste ca rasplata sabia zeului. ', 3, 1, 2),
('Frigg', 'Sotia lui odin', 'norse', 'In mitologia nordica, Frigg este sotia lui Odin mama lui Baldr, Hod si Wecta, zeita cerului, a mariajului si a fidelitatii. Puternica si tacuta, ea domneste pe tronul Hildskialf alaturi de Odin, tron de pe care se vede intregul univers. Frigg cunoaste destinul oamenilor si al zeilor, insa nu dezvaluie nimanui profetia sa. Pentru a preveni moartea fiului ei, Baldur, Frigg face intelegere cu toate fortele naturii pentru ca acestea sa nu-l omoare, insa uita vascul. Mesagerul lui Frigg este Gna. ', 3, 2, 4),
('Hephaestus', 'Zeul focului', 'greek', 'Hefaistos (in greaca veche Ἥφαιστος, Hephaistos) este, in mitologia greaca, zeul focului, al metalelor, al fierarilor, sculptorilor si artizanilor. Omologul lui Hefaistos, in mitologia romana, este Vulcan.\r\nIn mitologia greaca, Hefaistos era fie fiul lui Zeus si Hera, fie fiul partenogen al Herei. El a fost alungat din Olimp de catre mama sa din cauza deformatiilor sale, iar intr-o alta relatare, a fost aruncat de pe Muntele Olimp de Zeus pentru ca a protejat-o pe Hera de avansurile sale.[2]\r\nCa zeu fierar, Hefaistos a fabricat toate armele zeilor din Olimp. A slujit ca fierar al zeilor si a fost venerat in orasele industriale si centrele mestesugaresti din Grecia, in special Atena. Cultul lui Hefaistos a avut sediul in Lemnos. Simbolurile lui Hefaistos sunt ciocanul de fierar, nicovala si perechea de clesti. ', 4, 1, 1),
('Hera', 'Zeita Femeii', 'greek', 'Hera (in greaca veche Ήρα, Hera) este in mitologia greaca zeita protectoare a casniciei, a caminului si a femeilor maritate, precum si regina zeilor si a oamenilor. La romani este identificata cu Iunona.\r\nCa sotie a zeului suprem, ea era considerata protectoarea caminului, a casatoriei si, in general, a femeilor maritate. Avand ca simbol sceptrul, semn de conducere dar nu si de putere, Hera este adesea infatisata ca o sotie geloasa si nesabuit de violenta, care este usor de jignit si nu pregeta sa se razbune crunt pentru toate infidelitatile savarsite de sotul ei, Zeus. \r\nUna dintre primele instante ale numelui zeitei apare pe tablele din Pylos, scrise in Linearul B, un sistem de scriere care a fost gasit si pe datand inca din 1450 i.Hr. folosit de civilizatiile miceniene pana la colapsul acestora in secolul XII i.Hr. Aici apare ca Qo-wi-ja (Guowia „cea asemenea vacilor” un cunoscut epitet homeric).', 1, 1, 4),
('Hermes', 'Mesagerul zeilor', 'greek', 'Hermes este zeul mesager din mitologia greaca, fiul lui Zeus si al pleiadei Maia. Este considerat si protector al curierilor, pastorilor, cartoforilor, mincinosilor, hotilor negustorilor si oratorilor. Incaltat in sandale cu aripi, are capacitatea de a se misca rapid intre lumea pamanteasca si lumea divina. Acesta are rolul de a calauzi mortii in lumea de dincolo. Divinitatii ii sunt dedicate o serie de imnuri homerice.\r\nAtributele si simbolurile sale includ herma, cocosul, broasca testoasa, geanta sau punga, sandalele cu aripi si coiful cu aripi, precum si palmierul, capra, numarul patru, pestele si tamaia.\r\nDar cel mai important simbol este caduceul , un toiag inaripat impletit cu doi serpi copuland. Atributele sale sunt influentate de zeul etrusc Turms, un nume imprumutat de la grecescul \"herma\". In mitologia romana, Hermes este cunoscut si ca Mercur, un nume derivat din latinescul merx , care inseamna \"marfa\"', 3, 5, 2),
('Horus', 'Zeul cerului', 'egyptian', 'Horus a fost nascut de zeita Isis, care era virgina, dupa ce ea a adunat toate partile dezmembrate ale corpului sotului ei ucis, Osiris, cu exceptia penisului, care a fost aruncat in Nil si mancat de o balena. Ea si-a utilizat puterile magice pentru a-l reinvia pe Osiris si a creat adorarea unui falus de aur, pentru a-l concepe pe fiul ei. Intr-o alta versiune mitologica, Isis a ramas insarcinata cu ajutorul focului divin. Insarcinata cu Horus, Isis a fugit in mlastinile din Delta Nilului ca sa se ascunda de fratele ei Seth, cel care l-a ucis pe Osiris din gelozie si care voia sa-l omoare si pe fiul lor. Horus era sarbatorit in luna Noiembrie odata cu inceperea noului an. Surse tarzii atesta sarbatorirea lui Horus odata cu solstitiul de iarna (21 decembrie). ', 3, 2, 4),
('Idun', 'Zeita tineretii', 'norse', 'In mitologia nordica, Idunna este zeita tineretei eterne, sotia lui Bragi, zeul poeziei. Ea detine merele de aur ale tineretii. Cand un zeu simte batranetea apropiindu-se trebuie doar sa manance niste mere fermecate pentru a deveni din nou tanar. Idunna fost rapita de Thiazi, gigantul furtunii, iar in acea perioada, zeii au inceput sa imbatraneasca foarte mult. La rapire a contribuit si Loki, el fiind cel care a ademenit-o pe zeita sa iasa din Asgard. Zeii au aflat de fapta lui Loki si l-au pus sa o readuca pe Idun. Zeita a fost salvata de Loki, deghizat cu pielea de soim a Freyei, si astfel au reintinerit toti zeii. ', 1, 3, 5),
('Isis', 'Zeita vindecarii', 'egyptian', 'In mitologia si religia egipteana antica, Isis este zeita magiei, a vietii, a casatoriei, simbolul armoniei matrimoniale si fidelitatii femeii fata de sot. Sotia si sora lui Osiris, fiica zeilor Geb si Nut si mama lui Horus, Isis este una din principalele divinitati venerate de vechii egipteni. Ea apartine Eneadei de la Heliopolis, iar in epoca elenistica a devenit protectoarea marinarilor.\r\nNumele ei s-ar putea traduce prin „Regina tronului”, ea fiind o personificare a tronului faraonului si a puterii regale. Cu toate acestea, hieroglifa ei insemna la inceput „muritoare” si e posibil ca zeita sa fie o sinteza a mai multor regine egiptene deificate. ', 2, 1, 5),
('Khonsu', 'Zeul lunii', 'egyptian', 'Khonsu (de asemenea, Chonsu, Khensu, Khons, Chons sau Khonshu) este un stravechi zeu Egiptean al lunii. Numele lui inseamna \"calator\", si acest lucru se poate referi la calatoria lunii de pe cerul noptii. Impreuna cu Thoth a marcat trecerea timpului. Khonsu a avut un rol esential in crearea de o noua viata in toate creaturile vii.  ', 5, 5, 2),
('Loki', 'Zeul inselaciunii', 'norse', 'In mitologia nordica Loki este fiul gigantului Farbauti si al gigantei Laufey. Impreuna cu Odin a luat parte la actul antropogonic primordial, inoculandu-le primilor oameni, Askr si Embla, focul (flacara pasionala) si dandu-le chipul atragator si sangele. Traieste in Asgard alaturi de tribul Aesir, desi se dovedeste a fi dusmanul acestora. Este un zeu al focului si al magiei si poate lua mai multe forme, atat animale cat si umane. Este siret si malefic, fiind direct raspunzator pentru moartea lui Baldur. Intr-una din farsele sale i-a facut pe zei sa piarda temporar sursa lor de nemurire. Odata i-a furat ciocanul lui Thor, care a gasit din fericire un plan pentru a-l aduce inapoi. La un banchet a insultat zeii denuntindu-le secretele, lasitatea lui Bragi, prostitutia zeitelor Idunn si Frigg, incestul zeitei Freyja, reusind sa scape doar transformandu-se intr-un somon, dar nu a scapat totusi de Odin si a fost exilat intr-o pestera intunecata. Amanta sa este Angerbrode (Nascatoarea-de-tristete) cu care are trei copii monstruosi: Fenris lupul, marele sarpe Jormungand si zeita lumii subterane Hel (Moartea). Dintr-o a doua casnicie are doi fii: Vali si Narvi. In timpul exilului lui Loki, Vali avea sa se transforme intr-un lup si sa-l omoare pe Narvi. Sotia lui este Sigyn, cea care i-a fost loiala chiar si dupa ce Loki a fost pedepsit pentru moartea lui Baldur. Zeul a fost legat in pestera pomenita mai sus cu intestinele lui Narvi iar deasupra capului lui a fost pus un sarpe care scuipa venin. Sigyn culegea cu o cupa veninul sarpelui pentru a nu suferi sotul ei, insa cand mergea sa goleasca cupa, otrava curgea pe fata lui Loki. Durerea si zvarcolirea zeului provoca cutremure. Acolo avea sa astepte Ragnarok-ul unde a fost sortit sa conduca armata raului si sa fie omorat de Heimdall. ', 2, 3, 5),
('Mimir', 'Zeul cunoasterii', 'norse', 'Mimir (norvegiana veche: [ˈmiːmez̠]) sau Mim este o figura din mitologia nordica, renumita pentru cunostintele si intelepciunea sa, care este decapitat in timpul razboiului Æsir-Vanir. Dupa aceea, zeul Odin il poarta in jurul capului lui Mimir si ii recita cunostinte si sfaturi secrete.\r\nMimir este atestat in Edda poetica, compilata in secolul al XIII-lea din surse traditionale anterioare, Edda in proza, scrisa in secolul al XIII-lea de Snorri Sturluson din Islanda si in forma euhemerizata ca unul dintre Æsir din Heimskringla, scris si de Snorri Sturluson. in secolul al XIII-lea. Numele lui Mimir apare in numele fantanii Mimisbrunnr si numele Mimameiðr si Hoddmimis holt, pe care oamenii de stiinta le considera in general a fi nume pentru Yggdrasil. Savantii au propus ca Bestla ar putea fi sora lui Mimir si, prin urmare, Mimir ar fi unchiul matern (avunculus) al lui Odin.', 1, 1, 5),
('Njord', 'Zeul marii', 'norse', 'Njord (in limba urnordisk, Nerthuz) este zeul marii, al vanturilor si al focului in mitologia nordica. El aduce noroc calatorilor pe mare si vanatorilor. Este casatorit cu giganta Skadi, care l-a ales vazandu-i picioarele, despre care credea ca sunt ale lui Baldur.\r\nAre doi copii, Freyr si Freya, pe care i-a conceput cu propria sa sora.\r\nApartine tribului Vanir dar, cand acest trib a incheiat pacea cu dusmanii sai, tribul Aesir, Njord, impreuna cu copiii sai, i-au fost dati ca ostatici acestui trib.\r\nCei din tribul Aesir i-au numit pe Njord si Freyr preoti supremi pentru a prezida asupra sacrificiilor.\r\nFreya a fost numita preoteasa pentru sacrificii. Ea i-a invatat arta vrajitoriei pe cei din tribul Aesir, arta cunoscuta de toti cei din tribul Vanir. ', 3, 4, 3),
('Odin', 'Regele zeilor nordici', 'norse', 'Odin (oʊdIn din norvegiana veche: Oðinn [ˈoːðenː]) este un zeu venerat la scara larga in mitologia germanica. In general este descris ca rege al zeilor nordici. Mitologia nordica fiind sursa celor mai multe informatii supravietuitoare despre el,il asociaza pe Odin cu intelepciunea, vindecarea, moartea, regalitatea, spanzuratoarea, cunoasterea, razboiul, batalia, victoria, vrajitoria, poezia, frenezia si alfabetul runic si il descrie ca sotul zeitei Frigg. In mitologia si paganismul german , zeul era cunoscut in engleza veche sub numele de Woden, in saxona ca Wodan, in olandeza veche ca Wuodan, in friziana veche ca Weda si in limba germana veche ca Wuotan, toate derivand in cele din urma din cuvantul proto-germanic Wodanaz, care inseamna „stapanul freneziei”.\r\nOdin apare ca un zeu proeminent de-a lungul istoriei inregistrate a Europei de Nord, de la ocuparea romana a regiunilor Germaniei (din anul c. 2 i.e.n.) la marile migratii ale popoarelor in perioada secolelor IV-VI d.Hr., si in epoca vikinga (secolele VIII- XI d.Hr.). Referintele folclorice la el apar in nume de locuri in regiuni locuite istoric de vechile popoare germanice, iar ziua saptamanii de miercuri ii poarta numele in multe limbi germanice, inclusiv in engleza (wednesday). ', 5, 5, 5),
('Osiris', 'Zeul vietii de apoi', 'egyptian', 'In mitologia egipteana, Osiris este zeul vietii de apoi, al vegetatiei, fertilitatii, renasterii si al mortior. Era reprezentat ca o zeitate cu pielea verde, cu barba de faraon, partial infasurata ca o mumie, purtand o coroana de atef si tinand in mana un baston simbolic si un imblaciu.\r\n\r\nOsiris a fost un rege legendar al Egiptului, celebru prin vigoarea si dreptatea cu care isi guverna tara. Seth, fratele sau, a fost gelos pe el si i-a intins o cursa, reusind sa-l asasineze. Sotia lui Osiris, zeita Isis, reuseste sa ramana insarcinata cu Osiris mort. Dupa ce l-a ingropat pe Osiris, Isis se refugiaza in delta Nilului; acolo il aduce pe lume pe Horus, care, ajuns adult, isi face recunoscute drepturile in fata zeilor Enneadei si il ataca pe Seth. Horus il va invinge pe Seth in lupta, dar isi va pierde un ochi, pe care i-l ofera lui Osiris care astfel isi recapata viata. Seth va fi condamnat de zei sa-si poarte propria victima (fiind transformat in barca ce-l transporta pe Osiris, pe Nil). ', 3, 4, 2),
('Poseidon', 'Zeul marii', 'greek', 'In mitologia greaca, Poseidon (greaca Ποσειδῶν) era zeul marii, fiul lui Cronos si al Rheei.\r\nIn timpul epocii bronzului, Poseidon a fost venerat ca zeitate principala la Pylos si Teba. A purtat titlul de „cutremuratorul pamantului”. In Arcadia era inrudit cu Demetra si Persefona si a fost venerat ca zeu al apelor. El este adesea considerat tatal cailor. Conform unui mit, cu o lovitura a tridentului sau, a creat izvoarele din care au iesit primii cai din istorie.\r\nPoseidon a fost considerat protector al navigatorilor si al multor orase si colonii elene. Homer si Hesiod sugereaza ca Poseidon a devenit stapanul marii dupa infrangerea tatalui sau Cronos si stapanirea lumii a fost impartita la sorti intre cei trei fii ai sai; Zeus a primit cerul, Hades a primit lumea subterana, iar Poseidon a primit marea. In Iliada lui Homer, Poseidon ii sprijina pe greci impotriva troienilor in timpul razboiului troian. In Odiseea, in timpul calatoriei pe mare de la Troia inapoi spre casa sa din Itaca, eroul grec Ulise l-a maniat pe Poseidon pentru ca il orbise pe ciclopul Polifem, fiul lui Poseidon. Poseidon il pedepseste pe Ulise cu furtuni, pierderea corabiei si a echipajului sau si ii provoaca o intarziere de zece ani pe drumul spre Itaca. Poseidon este, de asemenea, subiectul unui imn homeric. Conform lui Platon, legendara insula Atlantida era domeniul lui Poseidon.', 4, 3, 1),
('Ptah', 'Zeul creator', 'egyptian', 'Ptah este zeul creator in Memphis, simbolizat printr-o mumie cu mainile intinse, tinand Sceptrul. Patronul spiritual al mestesugarilor, se extinde in a fi zeu creator, lumea nascandu-se din gandurile si cuvintele lui. Treptat devine o zeitate funerara, Ptah-Sokar-Osiris. S-a sugerat ca prin grecizarea numelui templului sau, Hwt-ka-Ptah in Aiguptos a deviat numele actual al tarii, Egipt. ', 5, 5, 5),
('Ra', 'Zeul soarelui', 'egyptian', 'Ra este zeul suprem din mitologia egipteana, personificare a soarelui. Era venerat la Heliopolis (Cetatea Soarelui). Reprezentarea obisnuita era a unui om cu un cap de soim si cu un disc solar deasupra capului.\r\nRa avea caracteristici comune cu zeul cerului, Horus. Uneori, cele doua zeitati erau contopite sub numele de Ra-Horakhty, \"Ra, care este Horus al celor doua orizonturi\". In Noul Regat, cand zeul Amun a devenit proeminent, a fost fuzionat cu Ra sub numele de Amun-Ra.\r\nSimbolurile lui Ra sunt discul si cercul cu un punct inauntru.\r\nSoarele este datatorul de viata, controland care au fost lucrate de om. Datorita calitatilor datatoare de viata ale soarelui, egiptenii il venerau ca pe un zeu. Creator al universului si datator de viata, Soarele sau Ra reprezenta viata, caldura si cresterea. Deoarece oamenii il considerau pe Ra ca fiind zeul principal, creatorul universului si sursa vietii, acesta a avut o influenta puternica asupra lor, ceea ce a facut ca el sa fie unul dintre cei mai venerati zei egipteni. In perioada timpurie a istoriei egiptene, influenta sa s-a raspandit in intreaga tara, aducand multiple reprezentari in forma si in nume. Cele mai frecvente combinatii de forme sunt cu Atum (forma sa umana), Khepri (gandacul scarabeu) si Horus (soimul). In varful capului sau se afla un disc solar cu o cobra, care in multe mituri reprezinta ochiul lui Ra. La inceputul timpului, cand nu exista decat haos, zeul-soare exista singur in masa acvatica a lui Nun care umplea universul.  ', 3, 2, 4),
('Seth', 'Zeul haosului', 'egyptian', 'In mitologia egipteana, Seth (scris si Set, Sutekh, Setesh, Seteh si Seti) este cunoscut drept fiu al lui Geb si al lui Nut, fratele lui Isis, Nephthys si Osiris. Seth este un zeu malefic, stapan al desertului, reprezentat cu cap de ogar cu coada lunga si cu botul alungit. \r\nLa inceput a fost considerat constructor de cetati, apoi zeul viguros al violentei, raului , intunericului si dezordinii, iar la un moment dat si zeu al razboiului (grecii il identificau cu Typhon).\r\nSe pare ca adeptii lui Seth s-au confruntat cu adeptii lui Horus si ai faraonului primei dinastii, Menes, care a unit Egiptul de Sus cu cel Egiptul de Jos. In aceasta privinta, Seth este infatisat punand la indoiala autoritatea fratelui sau Osiris. In drama care se petrece in religia egipteana, Seth intruchipeaza fortele potrivnice care aduc marea schimbare. In cele din urma infrant de Isis si de fiul sau, zeul soim Horus, Seth devine un spirit liber, un hoinar pe pamant si, dupa exilul sau fortat, zeul singuratatii pustii. ', 3, 2, 4),
('Shu', 'Zeul vantului', 'egyptian', 'Shu, in mitologia egipteana era Cel care rasare, zeu al aerului si al rasaritului. El separa cerul de pamant si aducea soarele la viata in fiecare dimineata, iar noaptea il pazea. Shu are forma umana, cu o pana (hieroglifa numelui sau) pe cap si cu bratele ridicate ce o sprijina pe zeita-cer Nut, pe care el o tine despartita de sotul ei, zeul-pamant Geb.\r\nEl este una dintre cele doua prime zeitati create de Atum, zeul-soare de la Heliopolis. S-a nascut la fel ca si sotia-sora a sa, Tefnut, din samanta lui Atum; ca o explicatie alternativa care implica un joc de cuvinte, Shu a aparut din mucusul pe care Atun l-a stranutat din narile sale.\r\nIn Textele Piramidelor, oasele lui Shu, probabil norii, sunt folosite de catre rege pentru a urca la cer. Lacurile lui Shu (poate ceata ce se aduna deasupra Nilului) il purifica pe monarh. Shu ca zeu al luminii solare este atestat pentru prima oara in Regatul Vechi, cand este responsabil cu aducerea la viata in fiecare zi a lui Ra si a regelui. Mai bine de o mie de ani mai tarziu, faraonul Akhnaton subliniaza aceasta idee descriindu-l pe Shu ca locuind discul solar.', 2, 5, 3),
('Thor', 'Zeul fulgerului', 'norse', 'In mitologia germanica, Thor (norvegiana veche: Þorr) este zeul asir asociat cu fulgerul, tunetul, furtuna, copacii si padurile sacre din paganismul si mitologia germanica, puterea, protectia omenirii, fertilitatea. In limba norvegiana veche este cunoscut ca Þorr, in engleza veche ca Þunor, in frizona veche ca Thuner, in saxona ca Thunar, si in germana veche ca Donar, toate rezultand in cele din urma din cuvantul proto-germanic Þun(a)raz, adica Tunet.\r\nThor este un zeu mentionat proeminent de-a lungul istoriei inregistrate a popoarelor germanice, din regiunile germanice aflate sub ocupatia romana la marile migratii germanice, de la la popularitatea sa ridicata in timpul epocii vikinge la crestinarea Scandinaviei. Emblema sa este ciocanul sau, Mjolnir.\r\nMitologia nordica, in mare parte consemnata in Islanda din materialele traditionale provenite din Scandinavia, ofera numeroase povesti cu zeul. In aceste surse, Thor poarta cel putin cincisprezece nume, este sotul zeitei cu parul auriu Sif, amanta sa este Jarnsaxa, si este in general descris ca fiind feroce, cu par roscat si barba rosie.', 5, 2, 1),
('Tyr', 'Zeul razboiului', 'norse', 'Tyrnorvegiana veche: Tyr, este zeul razboiului din mitologia germanica . In mitologia nordica care ofera cele mai multe dintre naratiunile supravietuitoare despre zei in randul popoarelor germanice, Tyr isi sacrifica mana lupului monstruos Fenrir care il musca cand isi da seama ca zeii l-au legat. Este prevestit ca Tyr va fi mancat de cainele monstruos Garmr in timpul evenimentelor din Ragnarok.\r\nDupa \"interpretarea romana\", este asociat cu zeul Marte, zeul roman al razboiului. Zeul este mentionat ca „Marte Thingsus” (latina „Marte al Adunarii”) pe o inscriptie latina din secolul III e.n., reflectand o asociere puternica cu adunarea germanica, un corp legislativ din randul popoarelor germane antice. Prin procesul opus al lui interpretatio germanica, ziua de marti din limba engleza poarta numele de Tyr , in vreme ce in limbile de origine latina poarta numele lui Marte. ', 5, 2, 4),
('Ymir', 'Zeul furtunii', 'norse', 'In mitologia nordica, Ymir (pronuntat cu accent \"EE-mir\") este un jotun care a fost creat cand focul din Muspelheim s-a intersectat (intalnit) cu gheata din Niflheim in abisul din Ginnungagap, astfel gheata din Niflheim s-a topit, iar stropii care s-au format au cazut pe pamant creandu-l pe Ymir.\r\nYmir mai este denumit si gigantul vietii pentru ca acesta a creat viata (Acesta nu a creat viata din cele 9 taramuri ale copacului Yggdrasill). ', 5, 1, 2),
('Zeus', 'Zeul cerului', 'greek', 'Zeus (in greaca veche Ζεύς) este zeul cerului si al tunetului in mitologia greaca. Acesta este regele zeilor de pe Muntele Olimp. Echivalentului sau roman este Jupiter, mitologia si puterile sale fiind similare, desi nu identice, si cu cele ale zeitatilor indo-europene precum Perkunas, Perun, Indra, Dyaus si Thor.\r\nZeus este copilul lui Cronos si Rhea, fiind cel mai tanar dintre fratii sai, desi este socotit drept pe cel mai mare, deoarece ceilalti frati (Hestia, Hades, Demetra, Poseidon, Hera) erau in stomacul lui Cronos. In majoritatea traditiilor, el este casatorit cu Hera, fiind tatal lui Ares, Hebe si Hefaistos. La oracolul Dodonei, consoarta sa era Dione, despre care Iliada afirma ca a fost tatal Afroditei. Zeus a fost, de asemenea, infam pentru escapadele sale erotice care au dus la multi descendenti divini si eroici, inclusiv Atena (fiica lui Metis, inghitita de Zeus), Apollo si Artemis (copiii lui Leto), Hermes (fiul pleiadei Maia), Persefona (fiica zeitei Demetra), Dionis (fiul lui Semele), Perseu (fiul lui Danae), Heracle (fiul lui Alcmena), Elena din Troia (fiica lui Leda), Minos (fiul lui Europa (mitologie)) si muzele.', 5, 5, 5);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `zei`
--
ALTER TABLE `zei`
  ADD PRIMARY KEY (`nume`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
